### ISSUE TITLE
Create custom fonts

### ISSUE THREAD

**Issue by colesnicov** [SuperHouse/esp-open-rtos#754]
Hello. I trying to create custom font by command:

`$ ./create_font.py -f ../../../res/fonts/ObelusCompact.ttf -n obelux_complact -c utf-8
`
And i get this error message..

```
Traceback (most recent call last):
  File "./create_font.py", line 89, in <module>
    main(parser.parse_args(sys.argv[1:]))
  File "./create_font.py", line 47, in main
    fnt = ImageFont.load(args.font)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 230, in load
    f._load_pilfont(filename)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 81, in _load_pilfont
    raise IOError("cannot find glyph data file")
OSError: cannot find glyph data file
```

**Comment by colesnicov** [comment]
Now works.

Replace this:

```
def main(args):
    fnt = ImageFont.load(args.font)
```

to:

```
def main(args):
    if args.truetype == 0: 
        fnt = ImageFont.load(args.font)
    else:
    # use a truetype font
        fnt = ImageFont.truetype(args.font, args.size)
```

And this:

   ```
 parser.add_argument('-s', '--size', type=int, help='Height for glyphs (default=8)', default=8)
    parser.add_argument('-ttf', '--truetype', type=int, required=True, help='TrueType font (0=no|1=yes)')
```

to:
`if __name__ == "__main__":`

Also you can modify **_template.c_** and add this line:

`#include <stdint.h>`
..

Regards..

**Comment by colesnicov** [comment]
6c993f9
